### ISSUE TITLE
Xcode build || signingIdentity & provisioningProfileUuid are required

### ISSUE THREAD

**Issue by nithinyell** [staff0rd/react-native-pipeline#2]
Use 

```
- task: Xcode@5
  displayName: "Build Mobile Application"
  inputs:
    actions: 'build'
    configuration: 'Release'
    xcWorkspacePath: 'Sample/ios/Sample.xcworkspace'
    scheme: 'sampleApp'
    sdk: 'iphoneos'
    packageApp: true
    exportPath: 'output/package'
    archivePath: 'output/archive'
    signingOption: 'manual'
    xcodeVersion: 'specifyPath'
    signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
    provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)'
    xcodeDeveloperDir: '/Applications/Xcode_11.7.app/Contents/Developer'
```
